import os

# Plex Configuration
PLEX_TOKEN = os.getenv('PLEX_TOKEN', '')
PLEX_URL = os.getenv('PLEX_URL', 'http://plex:32400') # Replace with your Plex IP

# Optional: Filter by Player Name (e.g. "Living Room TV")
# If set, lights will only change for this player.
TARGET_PLAYER_NAME = os.getenv('TARGET_PLAYER_NAME', '')

# # Tuya / Feit Configuration
# # List of lights to control. 
# # You can populate this manually or we can load from devices.json generated by tinytuya
LIGHTS = []
# If True, attempts to load from devices.json automatically
LOAD_FROM_JSON = True
